// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/rust/structs.mdx?collection=docs&hash=1749163124166"
import * as docs_8 from "../content/docs/rust/pattern_matching.mdx?collection=docs&hash=1749163124166"
import * as docs_7 from "../content/docs/rust/ownership.mdx?collection=docs&hash=1749163124166"
import * as docs_6 from "../content/docs/rust/index.md?collection=docs&hash=1749163124166"
import * as docs_5 from "../content/docs/rust/enums.mdx?collection=docs&hash=1749163124166"
import * as docs_4 from "../content/docs/rust/borrowing.mdx?collection=docs&hash=1749163124166"
import * as docs_3 from "../content/docs/devops/setup-vps-for-production.md?collection=docs&hash=1749163124166"
import * as docs_2 from "../content/docs/data-structures/list-adt.mdx?collection=docs&hash=1749163124166"
import * as docs_1 from "../content/docs/data-structures/linked-list.mdx?collection=docs&hash=1749163124166"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1749163124166"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"data-structures/linked-list.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/data-structures/linked-list.mdx"}, data: docs_1 }, { info: {"path":"data-structures/list-adt.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/data-structures/list-adt.mdx"}, data: docs_2 }, { info: {"path":"devops/setup-vps-for-production.md","absolutePath":"/home/charm/hiicharm/wiki/content/docs/devops/setup-vps-for-production.md"}, data: docs_3 }, { info: {"path":"rust/borrowing.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/borrowing.mdx"}, data: docs_4 }, { info: {"path":"rust/enums.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/enums.mdx"}, data: docs_5 }, { info: {"path":"rust/index.md","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/index.md"}, data: docs_6 }, { info: {"path":"rust/ownership.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/ownership.mdx"}, data: docs_7 }, { info: {"path":"rust/pattern_matching.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/pattern_matching.mdx"}, data: docs_8 }, { info: {"path":"rust/structs.mdx","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/structs.mdx"}, data: docs_9 }], [{"info":{"path":"data-structures/meta.json","absolutePath":"/home/charm/hiicharm/wiki/content/docs/data-structures/meta.json"},"data":{"title":"Data Structures","pages":["list-adt","linked-list"],"defaultOpen":false}}, {"info":{"path":"devops/meta.json","absolutePath":"/home/charm/hiicharm/wiki/content/docs/devops/meta.json"},"data":{"title":"DevOps","pages":["setup-vps-for-production"],"defaultOpen":false,"icon":"MyIcon"}}, {"info":{"path":"rust/meta.json","absolutePath":"/home/charm/hiicharm/wiki/content/docs/rust/meta.json"},"data":{"title":"Rust","pages":["index","ownership","borrowing","structs","enums","pattern_matching"],"defaultOpen":false,"icon":"MyIcon"}}])